FROM node:alpine

WORKDIR "/app"

COPY package.json .
RUN npm install

COPY . .

CMD [ "npm", "start" ]

# to override default start command to run tests
# docker run -it container_id/container_tag npm run test